### PR TITLE
Delete and Update old classes

### PR DESCRIPTION
**Pull request by eesung00**
Delete old classes related to addressbook.

Refactor the package `seedu.address` to `seedu.application`. 

Modified classes: 
* UIPartTest (change remove "old" naming in the class method)
* ParserUtil/ ParserUtilTest (remove depreciated code)

### CODE REVIEW

**Review by teekaytai — COMMENTED** [review]
Looking good! There's also these files to delete from `resources`
* address_book_32.png
* OldHelpWindow.fxml
* OldMainWindow.fxml
* PersonListCard.fxml
* PersonListPanel.fxml

I also noticed some deprecated items in Messages, CliSyntax and TypicalIndexes that can be deleted

**Comment by nmtuan2001** [comment]
I also have some deprecated codes in some Parser files. I can delete those parts after merging this PR too. Other than that, looks good

**Comment by eesung00** [comment]
> Looking good! There's also these files to delete from `resources`
> 
> * address_book_32.png
> * OldHelpWindow.fxml
> * OldMainWindow.fxml
> * PersonListCard.fxml
> * PersonListPanel.fxml
> 
> I also noticed some deprecated items in Messages, CliSyntax and TypicalIndexes that can be deleted

Fixed, thanks for spotting!

**Review by jhchee18 — COMMENTED** [review]
Looks good! Merged locally and dont find any old files. Let's merge first and see if any files are left off along the way 👍

**Pull request merged**
