### PR TITLE
Migrate to applications

### PR DESCRIPTION
**Pull request by teekaytai**
This PR changes the app to use `Applications` instead of `Persons`. The newly created files have been renamed to match the original files. The original files have not been deleted yet, but instead have been renamed to avoid a name collision. After the remaining replacement files have been created, all files related to `Person`, `AddressBook` or whose name starts with "Old" should be deleted.

<details>
<summary>The following files still need to be replaced</summary>

* `ClearCommand`
* `EditCommand`
* `FindCommand`
* `HelpCommand`
* `EditCommandParser`
* `FindCommandParser`
* Test files for each `Command` type
* `AddCommandIntegrationTest`
* `EditApplicationDescriptorTest` (originally `EditPersonDescriptorTest`)
* `ApplicationBookParserTest` (originally `AddressBookParserTest`)
* Tests for Parsers for `Delete`, `Edit` and `Find` commands
* `ParserUtilTest`
* `LogicManagerTest`
* Tests for the files in the `model.application` package
* `ApplicationBookTest` (originally `AddressBookTest`)
* `ModelManagerTest`
* `ApplicationBookBuilder`
* `EditApplicationDescriptionBuilder` (originally `EditPersonDescriptorBuilder`)
* `ApplicationUtil` (originally `PersonUtil`)
</details>

### CODE REVIEW

**Review by jhchee18 — COMMENTED** [review]
Uhh 111 files changed x.x Had a quick look on it, no major problem spotted. I think it is good to go.

**Comment by nmtuan2001** [comment]
@teekaytai I'm not one of the reviewers but just wondering if there is a reason to keep all the Old.... files around? Does it cause any errors if you just remove them? Sorry for asking, the files are all fine but I think without deleting anything, it's still somewhat the same as before, just with filenames changed?

**Comment by teekaytai** [comment]
> @teekaytai I'm not one of the reviewers but just wondering if there is a reason to keep all the Old.... files around? Does it cause any errors if you just remove them? Sorry for asking, the files are all fine but I think without deleting anything, it's still somewhat the same as before, just with filenames changed?

I considered it, but ultimately I thought it'd be more convenient for us to replace the files if we can see the files still there. Also partially deleting only some of the files felt inconsistent. So I opted to delete all the files in one shot later.

**Review by eesung00 — COMMENTED** [review]
LGTM 👍 

Just I have one question. Since all new classes starts with Application are deleted or to be deleted (those rename to Old), will the auto grading script shows that we did not contribute any code? (eg. the reposenselink)

**Comment by teekaytai** [comment]
> Just I have one question. Since all new classes starts with Application are deleted or to be deleted (those rename to Old), will the auto grading script shows that we did not contribute any code? (eg. the reposenselink)

Not sure actually... but I would hope not? If later on when we change the package name from "address" to "application", the file paths all change and reposense decides that someone has rewritten the whole code base, I would be pretty surprised

**Comment by eesung00** [comment]
> > Just I have one question. Since all new classes starts with Application are deleted or to be deleted (those rename to Old), will the auto grading script shows that we did not contribute any code? (eg. the reposenselink)
> 
> Not sure actually... but I would hope not? If later on when we change the package name from "address" to "application", the file paths all change and reposense decides that someone has rewritten the whole code base, I would be pretty surprised

image
Hmmm, I think we can hold on in merging this PR first. Let's confirm with tutor or prof.

**Comment by nmtuan2001** [comment]
> I considered it, but ultimately I thought it'd be more convenient for us to replace the files if we can see the files still there. Also partially deleting only some of the files felt inconsistent. So I opted to delete all the files in one shot later.

Oh yeah that's true. We wouldn't be able to copy files anymore.


> image Hmmm, I think we can hold on in merging this PR first. Let's confirm with tutor or prof.

But we have to do it within v1.2 though right? Although this PR hasn't changed any package names so it should be fine?

**Comment by eesung00** [comment]
> > image Hmmm, I think we can hold on in merging this PR first. Let's confirm with tutor or prof.
> 
> But we have to do it within v1.2 though right? Although this PR hasn't changed any package names so it should be fine?

But this PR deleted some of the classes starts with Application though. 💀 I am confirming with tutor now

**Comment by eesung00** [comment]
> > > image Hmmm, I think we can hold on in merging this PR first. Let's confirm with tutor or prof.
> > 
> > 
> > But we have to do it within v1.2 though right? Although this PR hasn't changed any package names so it should be fine?
> 
> But this PR deleted some of the classes starts with Application though. 💀 I am confirming with tutor now

Hi, got a reply from prof. Can proceed to merge this PR. The code authorship can be modified later through `@@author` described in [here](https://nus-cs2103-ay2223s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking). Sorry for the delay. 😭

**Pull request merged**
