### PR TITLE
Add tests for interview

### LINKED ISSUE #93: Add tests for Interview and new methods added.
Sub task for #44 and #49

### PR DESCRIPTION
**Pull request by jhchee18**
Resolves #93

### CODE REVIEW

**Review by nmtuan2001 — COMMENTED** [review]
LGTM!

**Review by jolynloh — COMMENTED** [review]
LGTM though I'm not sure why it's not passing checks. Maybe push the branch again so the checks can re-run?

**Comment by eesung00** [comment]
> LGTM though I'm not sure why it's not passing checks. Maybe push the branch again so the checks can re-run?

image

its codecov error, can try run the check again from here. It will success eventually.

**Comment by jhchee18** [comment]
Thanks all for the solutions!

**Pull request merged**
