### PR TITLE
Modify UI to include label for date applied

### LINKED ISSUE #89: Clarify that the date of the application is the date applied
Add a label to the UI that explains the date is date applied.  
Also change 'DATE' to 'DATE_APPLIED' in the AddCommand and EditCommand usage instruction.

### PR DESCRIPTION
**Pull request by jolynloh**
Included a small label above application list to explain the meaning of the dates

image

### CODE REVIEW

**Review by nmtuan2001 — COMMENTED** [review]
Looks good! Thanks for adding this!

**Review by teekaytai — COMMENTED** [review]
It would also be good to change the `d/DATE` to `d/DATE_APPLIED` in the usage message in the `AddCommand` and `EditCommand` classes
Also, personally I think the UI label is a bit _too_ faint, kinda hard to read. 😅 Not sure what the rest think though

Thanks for working on this!

**Comment by jolynloh** [comment]
> It would also be good to change the `d/DATE` to `d/DATE_APPLIED` in the usage message in the `AddCommand` and `EditCommand` classes Also, personally I think the UI label is a bit _too_ faint, kinda hard to read. 😅 Not sure what the rest think though
> 
> Thanks for working on this!

oh right thanks for pointing out edits for the command classes. 

For the UI  label, how's this instead? 😅

image

Not sure if it looks out of place? But definitely easier on the eyes compared to the previous one. What do the rest think? @nmtuan2001 @eesung00 @jhchee18

**Comment by nmtuan2001** [comment]
> Not sure if it looks out of place? But definitely easier on the eyes compared to the previous one. What do the rest think? @nmtuan2001 @eesung00 @jhchee18

I think it looks fine. I get why you asked if it looks out of place though, but not really sure how to make it better. For now, it's fine imo.

**Comment by eesung00** [comment]
> > It would also be good to change the `d/DATE` to `d/DATE_APPLIED` in the usage message in the `AddCommand` and `EditCommand` classes Also, personally I think the UI label is a bit _too_ faint, kinda hard to read. 😅 Not sure what the rest think though
> > Thanks for working on this!
> 
> oh right thanks for pointing out edits for the command classes.
> 
> For the UI label, how's this instead? 😅
> 
> image
> 
> Not sure if it looks out of place? But definitely easier on the eyes compared to the previous one. What do the rest think? @nmtuan2001 @eesung00 @jhchee18

I think we might need to keep it similar width x height with the original one? Not sure is for mock UI only or general UI size
image

**Comment by nmtuan2001** [comment]
> I think we might need to keep it similar width x height with the original one? Not sure is for mock UI only or general UI size image

Probably just for mock UI imo but we can check just in case

**Comment by jhchee18** [comment]
Looks clean and clear! 👍 Just another thought maybe we can refine the UI as 

> 1. Google
> Contact: 68882888
> Position: Software Engineer Intern
> Email: xxx@google.com
> Date applied: Sep 10 2022

Since we got space to expand it horizontally, instead of eating up space for vertical scrolling.

Anyway, this is good enough already!

**Comment by jolynloh** [comment]
> > > It would also be good to change the `d/DATE` to `d/DATE_APPLIED` in the usage message in the `AddCommand` and `EditCommand` classes Also, personally I think the UI label is a bit _too_ faint, kinda hard to read. 😅 Not sure what the rest think though
> > > Thanks for working on this!
> > 
> > 
> > oh right thanks for pointing out edits for the command classes.
> > For the UI label, how's this instead? 😅
> > image
> > Not sure if it looks out of place? But definitely easier on the eyes compared to the previous one. What do the rest think? @nmtuan2001 @eesung00 @jhchee18
> 
> I think we might need to keep it similar width x height with the original one? Not sure is for mock UI only or general UI size image

For this, I didn't actually change the default width and height, just maximised the window here so easier to see 😅

**Comment by jolynloh** [comment]
> Looks clean and clear! 👍 Just another thought maybe we can refine the UI as
> 
> > 1. Google
> >    Contact: 68882888
> >    Position: Software Engineer Intern
> >    Email: [xxx@google.com](mailto:xxx@google.com)
> >    Date applied: Sep 10 2022
> 
> Since we got space to expand it horizontally, instead of eating up space for vertical scrolling.
> 
> Anyway, this is good enough already!

hmm yeah I thought about it as well, but since the contact, position and email fields are pretty intuitive, I thought that including it would clutter up the space since there is not much value-add. Anyway, thanks for the suggestion! I'll go ahead with the one-liner label in brighter font and we can always change it afterwards if we want to

**Comment by eesung00** [comment]
> > > > It would also be good to change the `d/DATE` to `d/DATE_APPLIED` in the usage message in the `AddCommand` and `EditCommand` classes Also, personally I think the UI label is a bit _too_ faint, kinda hard to read. 😅 Not sure what the rest think though
> > > > Thanks for working on this!
> > > 
> > > 
> > > oh right thanks for pointing out edits for the command classes.
> > > For the UI label, how's this instead? 😅
> > > image
> > > Not sure if it looks out of place? But definitely easier on the eyes compared to the previous one. What do the rest think? @nmtuan2001 @eesung00 @jhchee18
> > 
> > I think we might need to keep it similar width x height with the original one? Not sure is for mock UI only or general UI size image
> 
> For this, I didn't actually change the default width and height, just maximised the window here so easier to see 😅

Oh haha then should be fine. Yup other than that looks good to me.

**Pull request merged**
