### PR TITLE
Update AboutUs page

### LINKED ISSUE #4: Update AboutUs.md
This page (in the /docs folder) is used for module admin purposes. Must be done by every team member.
Mark done:

- [x] JH
- [x] TK
- [x] Jolyn
- [x] ES
- [x] MT

### PR DESCRIPTION
**Pull request by jolynloh**

### CODE REVIEW

**Review by teekaytai — APPROVED** [review]
lgtm

**Comment by eesung00** [comment]
Take note that image file naming has error (jolynloh.png.jpeg)

**Comment by teekaytai** [comment]
Oh yeah... my bad for not noticing before merging.
Seems like the image is not being detected on the [team list page](https://nus-cs2103-ay2223s1.github.io/website/admin/teamList.html). It's probably easier to change the picture format from a `.jpeg` to a `.png` rather than figure out what they mean by "name the file as `.png` anyway"

**Comment by eesung00** [comment]
image

If you are using windows, in your File Explorer `View > File name extension ` need to be checked before renaming the file.

I think Jolyn did not checked this box and renaming it to `.png `which cause the filename to be `jolynloh.png.jpeg` 😅

**Comment by teekaytai** [comment]
Oh wot I didn't know you could convert image format by just renaming the file extension o.O
Ok so that must be what the instructions meant

**Comment by jolynloh** [comment]
thanks for pointing this out 😄

**Pull request merged**
