### PR TITLE
Update JH AboutUs page

### LINKED ISSUE #4: Update AboutUs.md
This page (in the /docs folder) is used for module admin purposes. Must be done by every team member.
Mark done:

- [x] JH
- [x] TK
- [x] Jolyn
- [x] ES
- [x] MT

### PR DESCRIPTION
**Pull request by jhchee18**
Update AboutUs page and include personal photo

### CODE REVIEW

**Review by jolynloh — COMMENTED** [review]
lgtm

**Review by jolynloh — COMMENTED** [review]
lgtm

**Review by nmtuan2001 — APPROVED** [review]
lgtm

**Comment by nmtuan2001** [comment]
Looks like there is a conflict here. I can fix it later together with my own one

**Comment by jhchee18** [comment]
@nmtuan2001 it's okay, I fixed it just now

**Comment by nmtuan2001** [comment]
> @nmtuan2001 it's okay, I fixed it just now

ok cool

**Pull request merged**
